### ISSUE TITLE
Custom title bar of R GUI on Windows

### ISSUE THREAD

**Issue by abmaidman** [randy3k/SendCode#48] opened 2017-08-02 15:05 UTC
I am working on a Windows machine and I am trying to send a line of R-code to the Rgui.  When I hit ctrl+enter, I advance to the next line in R-Box, but nothing gets sent to the Rgui.  I have tried this with cmder and I still have the same problems.  My issue seems related to other issues, but I haven't been able to figure out my issue from reading others on this thread.

I have the R-Box and Terminal packages installed.  I am pretty sure that I have the correct path to Rgui ("C:\\Program Files\\R\\R-3.4.1\\bin\\x64\\Rgui.exe") because the terminal package opens up the correct window.

Any suggestions?  I attached my sendcode settings.  Do I need to change naything in the R-Box settings?

![sendcodesettings](https://user-images.githubusercontent.com/15932127/28880251-0f4f79f8-776a-11e7-9428-a4701cb2aaee.PNG)

**Comment by randy3k** [comment] 2017-08-02 15:18
There is no path setting for arguing, SendCode finds it automatically, I am not sure why it cannot be found. For Cmder or Conemu, you should provide the path to ConEmuC.exe and the setting name should be 'conemuc'.

**Comment by randy3k** [comment] 2017-08-02 15:20
In fact, you should remove the setting `r`, the path to Rgui, it will break the functionality of SendCode.

**Comment by abmaidman** [comment] 2017-08-02 19:26
Thanks.  I provided the path for ConEmuC.exe and now SendCode is working for both cmder and conemu, although there is quite a bit of lag between when I send the code and when it appears in the terminal which is strange.

I would really like to be able to use Rgui because I prefer my customized color scheme there (different colors for input and output) and it automatically loads my R User Profile.  Any idea what is going on?

**Comment by randy3k** [comment] 2017-08-02 19:29
Are there any error messages in the sublime console?
I don't have control about the lag, you would report to conemu or Cmder for this issue.

**Comment by abmaidman** [comment] 2017-08-02 19:34
There are no errors in the sublime console.

**Comment by randy3k** [comment] 2017-08-02 22:54
That's strange, sth obvious, was the file opened a R file?

**Comment by randy3k** [comment] 2017-08-02 22:56
Also, you need to open R GUI first.

**Comment by abmaidman** [comment] 2017-08-02 23:22
I do have RGui opened first.  The path to the RGui is C:\Program Files\R\R-3.4.1\bin\x64\Rgui.exe (probably not relevant).  I have an R file opened and I set the syntax to R-Extended (from R-Box).

Everything used to work fine for me, but it stopped working about a month ago.  I think (but am not certain) that I upgraded from R 3.4.0 to R 3.4.1 around the same time I started to have this problem.  I'm not sure if that's relevant.

**Comment by randy3k** [comment] 2017-08-05 06:43
I just tried R Gui on windows and it is still working fine for me. It should not be a issue of R 3.4.1.

**Comment by abmaidman** [comment] 2017-08-05 21:10
After trying more things, I may have isolated the problem.  When I have the Rconsole file which allows for customization in my home directory (in windows it is the Documents directory by default), SendCode does not work with R Gui.  When I remove the file (and default, uncustomized R Gui opens), everything works fine.

I included a .txt version of my Rconsole file here.  The actual Rconsole file is saved as Rconsole (with no extension).
[Rconsole.txt](https://github.com/randy3k/SendCode/files/1202681/Rconsole.txt)

**Comment by abmaidman** [comment] 2017-08-05 21:38
Further experimentation shows that when line 7 is changed to "MDI = yes", everything works fine.  So having "MDI = no" seems to be causing the problem.  

I strongly prefer MDI = no because it opens up graphics and other windows in a seperate window (outside of the Rgui window) and I can move them around my screen.

**Comment by randy3k** [comment] 2017-08-05 22:11
SendCode also supports SDI and I have just tried using your Rconsole settings, it works for me too.

<img width="955" alt="screen shot 2017-08-05 at 6 11 07 pm" src="https://user-images.githubusercontent.com/1690993/28999110-7b91d966-7a09-11e7-82d7-a62d77c4d70a.png">

**Comment by randy3k** [comment] 2017-08-05 22:19
SendCode uses PyWin32 to find R Gui, would you try running the following in Sublime Text console.

```
>>> import win32gui; win32gui.FindWindow("Rgui", "R Console (64-bit)")
1049712
```
it should returns a non-zero number if it finds the Rgui window.

**Comment by abmaidman** [comment] 2017-08-05 22:26
>>> import win32gui; win32gui.FindWindow("Rgui", "R Console (64-bit)")
0

It returned a 0.

**Comment by abmaidman** [comment] 2017-08-05 23:45
I just removed Sendcode and then reinstalled it.  After choosing R Gui to be my program and then hitting ctrl+enter, still nothing sends and I now have this error in the console  (SendCode settings are attached)
![sendcodesettings](https://user-images.githubusercontent.com/15932127/28999498-414974d0-7a0e-11e7-8954-19568b72274c.PNG)


Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "C:\Users\Adam\AppData\Roaming\Sublime Text 3\Packages\SendCode\send_code.py", line 68, in run
    getter = TextGetter.initialize(self.view)
  File "C:\Users\Adam\AppData\Roaming\Sublime Text 3\Packages\SendCode\text_getter\getter.py", line 17, in initialize
    syntax = Settings(view).syntax()
  File "C:\Users\Adam\AppData\Roaming\Sublime Text 3\Packages\SendCode\settings.py", line 58, in __init__
    self.s = sublime.load_settings("SendCode.sublime-settings")
AttributeError: 'NoneType' object has no attribute 'load_settings'

**Comment by randy3k** [comment] 2017-08-06 01:15
That's strange. Is the title of the window same as mine? "R Console..."?

I guess the error is caused by the not fully loaded Sublime Text, would you try again?

**Comment by abmaidman** [comment] 2017-08-06 23:35
In addition to my Rconsole file, I also have an Rprofile file (attached) in my home directory.  It is saved 
as a file with no name, but it has a .Rprofile extension.  The command in line 2, changes the title to the directory in which the R Gui was opened (works nicely with the Terminal package and when I have several R GUI windows open at the same time).  When it is commented out, everything works fine, but when I leave that line in, SendCode doesn't send over the line.

I can live with not being able to customize the title of my RGui windows, so I guess my problem has been solved.  It would be nice though to be able to have 1 R GUI window called "R Console C:/Project_1" and another called "R Console C:/Project_2".

[Rprofile.txt](https://github.com/randy3k/SendCode/files/1203541/Rprofile.txt)

**Comment by randy3k** [comment] 2017-08-06 23:53
Thanks for the information. SendCode currently only searches for window named as "R Console (64-bit)" or "R Console (32-bit)". Will try to fix the customize title bar issue.

**Comment by abmaidman** [comment] 2017-08-07 00:02
Glad we finally identified the problem.  I should mention that I have always been using SendCode with a custom R Gui window title in SDI, and that everything has worked fine until about late June.

**Comment by randy3k** [comment] 2017-08-07 03:43
Then it is strange, SendCode only searches  "R Console (64-bit)" or "R Console (32-bit)". It should not be working with a custom title.

**Comment by randy3k** [comment] 2017-08-07 03:45
Let's keep this issue until it's fixed.

**Comment by randy3k** [comment] 2017-08-09 03:20
it should be fixed at 0.3.1. @abmaidman, could you test it?

**Comment by abmaidman** [comment] 2017-08-09 13:20
I added this to my user keybinds, and evertyhing is working fine.  I think the issue can be closed now.

    {
        "keys": ["ctrl+shift+j"], "command": "send_code",
        "args": {"cmd":  "utils::setWindowTitle(\"$file\")"},
        "context": [
            { "key": "selector", "operator": "equal", "operand": "source.r" }
        ]
    }

**Comment by randy3k** [comment] 2017-08-09 15:10
Thanks for testing.

**Closed** 2017-08-09 15:11 UTC
